export const SETTINGS_DEFAULTS = {
  includeSvg: false,
  cursorSize: 32,
  outlineColor: '#ff9900',
  outlineWidth: 2,
  insetWidth: 2,
  cursorEmoji: '📌',
  multiCursorEmoji: '📝',
  badgeBgColor: '#3399ff',
  flashFontSize: 13,
  flashFontColor: '#ffffff',
  flashBgColor: 'rgba(0,0,0,0.8)',
  flashPause: 400,
  flashDuration: 1500,
  flashFallDistance: 80,
  cursorOffsetX: -6,
  cursorOffsetY: -6,
  facingX: 0,
  facingY: -1,
  facingBounds: 0,
  optionsFontSize: 14,
  optionsFontColor: '#000000',
  optionsBgColor: '#ffffff',
  sectionBgColor: 'rgba(0,0,0,0.06)',
  offsetMax: 10,
  savedFlashDuration: 1500,
}

export type Settings = typeof SETTINGS_DEFAULTS
