// AUTO-GENERATED by scripts/gen-elements.ts
export const SETTINGS_DEFAULTS = {
  cursorEmoji       : '👆',
  multiCursorEmoji  : '📋',
  cursorSize        : 32,
  cursorOffsetX     : -10,
  cursorOffsetY     : -10,
  outlineColor      : '#c2934c',
  outlineWidth      : 4,
  insetWidth        : 4,
  toastFontSize     : 20,
  flashPause        : 0,
  flashDuration     : 2000,
  flashFallDistance : 450,
  flashFontColor    : '#ffffff',
  flashBgColor      : '#000000cc',
  optionsFontSize   : 22,
  optionsFontColor  : '#ffffff',
  optionsBgColor    : '#000000',
  sectionBgColor    : '#121212',
  badgeBgColor      : '#3399ff',
  badgeFontColor    : '#ffffff',
  badgeFontSize     : 13,
  offsetMax         : 16,
  savedFlashDuration: 1500,
  includeSvg        : false,
}

export type Settings = typeof SETTINGS_DEFAULTS
// AUTO-GENERATED by scripts/gen-elements.ts
