export const SETTINGS_DEFAULTS = {
  multiSelectKey    : 'auto',
  cursorEmoji       : '👆',
  multiCursorEmoji  : '📋',
  cursorSize        : 32,
  cursorOffsetX     : -10,
  cursorOffsetY     : -10,
  outlineColor      : '#c2934c',
  outlineWidth      : 4,
  insetWidth        : 4,
  toastFontSize     : 20,
  flashPause        : 0,
  flashDuration     : 2000,
  flashFallDistance : 450,
  flashFontColor    : '#ffffff',
  flashBgColor      : '#000000cc',
  badgeBgColor      : '#3399ff',
  badgeFontColor    : '#ffffff',
  badgeFontSize     : 13,
  badgePulse        : true,
  badgePulseDuration: 1000,
  badgePulseScale   : 120,
  optionsFontSize   : 22,
  optionsFontColor  : '#ffffff',
  optionsBgColor    : '#000000',
  sectionBgColor    : '#121212',
  resetBtnSize      : 14,
  resetBtnColor     : '#ffffff66',
  previewSize       : 96,
  offsetMax         : 16,
  savedFlashDuration: 1500,
  includeSvg        : false,
}

export type Settings = typeof SETTINGS_DEFAULTS
