export const SETTINGS_DEFAULTS = {
  includeSvg: false,
  cursorSize: 32,
  outlineColor: '#c2934c',
  outlineWidth: 4,
  insetWidth: 4,
  cursorEmoji: '👆',
  multiCursorEmoji: '📋',
  badgeBgColor: '#3399ff',
  badgeFontColor: '#ffffff',
  badgeFontSize: 13,
  flashFontSize: 20,
  flashFontColor: '#ffffff',
  flashBgColor: 'rgba(0,0,0,0.8)',
  flashPause: 0,
  flashDuration: 2000,
  flashFallDistance: 450,
  cursorOffsetX: -10,
  cursorOffsetY: -10,
  facingX: -1,
  facingY: 1,
  facingBounds: 0,
  optionsFontSize: 22,
  optionsFontColor: '#ffffff',
  optionsBgColor: '#000000',
  sectionBgColor: '#121212',
  offsetMax: 16,
  savedFlashDuration: 1500,
}

export type Settings = typeof SETTINGS_DEFAULTS
