export const els = {
  get cursorEmojiBtn     () { return document.getElementById('cursorEmojiBtn') as HTMLButtonElement },
  get multiCursorEmojiBtn() { return document.getElementById('multiCursorEmojiBtn') as HTMLButtonElement },
  get cursorSize         () { return document.getElementById('cursorSize') as HTMLInputElement },
  get offsetCoords       () { return document.getElementById('offsetCoords') as HTMLSpanElement },
  get offsetPlane        () { return document.getElementById('offsetPlane') as HTMLDivElement },
  get offsetDot          () { return document.getElementById('offsetDot') as HTMLDivElement },
  get outlineColor       () { return document.getElementById('outlineColor') as HTMLInputElement },
  get outlineWidth       () { return document.getElementById('outlineWidth') as HTMLInputElement },
  get insetWidth         () { return document.getElementById('insetWidth') as HTMLInputElement },
  get toastFontSize      () { return document.getElementById('toastFontSize') as HTMLInputElement },
  get flashPause         () { return document.getElementById('flashPause') as HTMLInputElement },
  get flashDuration      () { return document.getElementById('flashDuration') as HTMLInputElement },
  get flashFallDistance  () { return document.getElementById('flashFallDistance') as HTMLInputElement },
  get flashFontColor     () { return document.getElementById('flashFontColor') as HTMLInputElement },
  get flashBgColor       () { return document.getElementById('flashBgColor') as HTMLInputElement },
  get optionsFontSize    () { return document.getElementById('optionsFontSize') as HTMLInputElement },
  get optionsFontColor   () { return document.getElementById('optionsFontColor') as HTMLInputElement },
  get optionsBgColor     () { return document.getElementById('optionsBgColor') as HTMLInputElement },
  get sectionBgColor     () { return document.getElementById('sectionBgColor') as HTMLInputElement },
  get badgeBgColor       () { return document.getElementById('badgeBgColor') as HTMLInputElement },
  get badgeFontColor     () { return document.getElementById('badgeFontColor') as HTMLInputElement },
  get badgeFontSize      () { return document.getElementById('badgeFontSize') as HTMLInputElement },
  get offsetMax          () { return document.getElementById('offsetMax') as HTMLInputElement },
  get savedFlashDuration () { return document.getElementById('savedFlashDuration') as HTMLInputElement },
  get includeSvg         () { return document.getElementById('includeSvg') as HTMLInputElement },
  get copyJsonBtn        () { return document.getElementById('copyJsonBtn') as HTMLButtonElement },
  get applyJsonBtn       () { return document.getElementById('applyJsonBtn') as HTMLButtonElement },
  get exportBtn          () { return document.getElementById('exportBtn') as HTMLButtonElement },
  get importFile         () { return document.getElementById('importFile') as HTMLInputElement },
  get configJson         () { return document.getElementById('configJson') as HTMLTextAreaElement },
  get status             () { return document.getElementById('status') as HTMLParagraphElement },
}
