import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { SECTIONS, ADVANCED_FIELDS } from '../src/options-fields'
import type { FieldDef } from '../src/options-fields'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const FIELD_TYPE_TO_TAG: Partial<Record<FieldDef['type'], keyof HTMLElementTagNameMap>> = {
  number:   'input',
  color:    'input',
  checkbox: 'input',
  emoji:    'button',
}

const TAG_TO_HTML_TYPE: Partial<Record<keyof HTMLElementTagNameMap, string>> = {
  input:    'HTMLInputElement',
  button:   'HTMLButtonElement',
  div:      'HTMLDivElement',
  span:     'HTMLSpanElement',
  textarea: 'HTMLTextAreaElement',
  p:        'HTMLParagraphElement',
  select:   'HTMLSelectElement',
}

function htmlType(tag: keyof HTMLElementTagNameMap): string {
  return TAG_TO_HTML_TYPE[tag] ?? 'HTMLElement'
}

// Collect { id, tag } from all field defs
const fieldEntries: Array<{ id: string; tag: keyof HTMLElementTagNameMap }> = []
const allFields = [...SECTIONS.flatMap(s => s.fields), ...ADVANCED_FIELDS]

for (const f of allFields) {
  if (f.type === 'plane') {
    for (const entry of f.ids) fieldEntries.push(entry)
  } else {
    const tag = FIELD_TYPE_TO_TAG[f.type]
    if (tag) fieldEntries.push({ id: f.id, tag })
  }
}

// Collect static IDs from options.html (those not already in fieldEntries)
const fieldIds = new Set(fieldEntries.map(e => e.id))
const html = readFileSync(resolve(root, 'options.html'), 'utf8')
const staticEntries: Array<{ id: string; tag: keyof HTMLElementTagNameMap }> = []

const validIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/
for (const match of html.matchAll(/<(\w+)[^>]*\sid="([^"]+)"/g)) {
  const [, tag, id] = match
  if (!fieldIds.has(id) && validIdentifier.test(id)) {
    staticEntries.push({ id, tag: tag.toLowerCase() as keyof HTMLElementTagNameMap })
  }
}

// Emit
const allEntries = [...fieldEntries, ...staticEntries]
const maxIdLen = Math.max(...allEntries.map(e => e.id.length))

const lines = allEntries.map(({ id, tag }) => {
  const padded = id.padEnd(maxIdLen)
  return `  get ${padded}() { return document.getElementById('${id}') as ${htmlType(tag)} },`
})

const output = `// AUTO-GENERATED by scripts/gen-elements.ts
export const els = {
${lines.join('\n')}
}
`

writeFileSync(resolve(root, 'src/options-elements.ts'), output)
console.log(`wrote src/options-elements.ts (${allEntries.length} entries)`)
